#!/usr/bin/env bash
# Pick a backdrop for Ghostty and write it into ~/.config/ghostty/backdrop.conf.
#
# Ghostty reads its config once at launch and has no scripting hook, so
# wallpaper rotation lives here instead: this writes the include file and
# Ghostty picks it up on its next config reload (CMD+SHIFT+,).
set -euo pipefail

BACKDROP_DIR="${GHOSTTY_BACKDROP_DIR:-$HOME/.config/ghostty/backdrops}"
CONF_DIR="${GHOSTTY_CONFIG_DIR:-$HOME/.config/ghostty}"
CONF="$CONF_DIR/backdrop.conf"
STATE="$CONF_DIR/.backdrop-index"

# Only the dark frames: selected by mean greyscale luminance with the cutoff at
# 0.30, where the folder splits cleanly. Lighter frames wash out Catppuccin
# Mocha's foreground.
BACKDROPS=(
   'astro-jelly.jpg'    # 0.10
   'totoro.jpeg'        # 0.14
   '6798923.jpg'        # 0.15
   'space.jpg'          # 0.17
   'voyage.jpg'         # 0.18
   'sword.jpg'          # 0.20
   '4356396.jpg'        # 0.22
   'cloudy-quasar.png'  # 0.23
   '5-cm.jpg'           # 0.25
   'cherry-lava.jpg'    # 0.28
   'nord-space.png'     # 0.29
)

# Ghostty has no layer stack for a dimming scrim, so the image is blended
# against the theme background at a low alpha instead: dark enough that bright
# regions of the wallpaper can't eat the foreground.
IMAGE_OPACITY="${GHOSTTY_BACKDROP_OPACITY:-0.18}"

usage() {
   cat <<'USAGE'
usage: backdrop.sh [next|prev|random|<filename>] [--reload]

   next        advance one frame (default)
   prev        go back one frame
   random      pick any frame
   <filename>  use that file from the backdrop dir
   --reload    best-effort: send Ghostty its reload-config shortcut afterwards
USAGE
}

# Drop anything that isn't actually on disk -- the images are third-party
# wallpapers and deliberately not vendored, so a fresh machine has fewer.
available=()
for name in "${BACKDROPS[@]}"; do
   [ -f "$BACKDROP_DIR/$name" ] && available+=("$name")
done

if [ ${#available[@]} -eq 0 ]; then
   echo "backdrop.sh: no listed wallpapers found in $BACKDROP_DIR" >&2
   echo "drop JPEG/PNGs there, or point GHOSTTY_BACKDROP_DIR somewhere else" >&2
   exit 1
fi

mode='next'
reload=false
for arg in "$@"; do
   case "$arg" in
      --reload) reload=true ;;
      -h | --help)
         usage
         exit 0
         ;;
      *) mode="$arg" ;;
   esac
done

index=0
[ -f "$STATE" ] && index="$(cat "$STATE")"
[ "$index" -ge 0 ] 2>/dev/null || index=0

case "$mode" in
   next) index=$(((index + 1) % ${#available[@]})) ;;
   prev) index=$(((index - 1 + ${#available[@]}) % ${#available[@]})) ;;
   random) index=$((RANDOM % ${#available[@]})) ;;
   *)
      found=-1
      for i in "${!available[@]}"; do
         [ "${available[$i]}" = "$mode" ] && found="$i"
      done
      if [ "$found" -lt 0 ]; then
         echo "backdrop.sh: '$mode' is not an available backdrop" >&2
         printf '%s\n' "${available[@]}" >&2
         exit 1
      fi
      index="$found"
      ;;
esac

image="$BACKDROP_DIR/${available[$index]}"

mkdir -p "$CONF_DIR"
cat > "$CONF" <<CONF
# Generated by backdrop.sh -- edits here are overwritten. Included from config.
background-image = $image
# cover, not contain: a letterboxed image would show the bare background
# colour down the sides of a full-width quick terminal.
background-image-fit = cover
background-image-position = center
background-image-opacity = $IMAGE_OPACITY
CONF
echo "$index" > "$STATE"

echo "backdrop -> ${available[$index]}"

if [ "$reload" = true ] && pgrep -xq ghostty; then
   # Ghostty exposes no reload verb to AppleScript, so this presses the
   # reload_config binding. Needs Automation permission for the calling app;
   # pressing CMD+SHIFT+, in Ghostty yourself does the same thing.
   osascript -e 'tell application "Ghostty" to activate' \
      -e 'tell application "System Events" to keystroke "," using {command down, shift down}' \
      > /dev/null 2>&1 || echo "reload failed; press CMD+SHIFT+, in Ghostty" >&2
fi
